# Generated by Django 5.1.3 on 2024-11-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
