# Generated by Django 5.1.3 on 2024-11-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_remove_comment_post_comment_author_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
